### ISSUE TITLE
Pressing "History Back" after renaming frame throws error

### ISSUE THREAD

**Issue by joerghampel** [JKISoftware/JKI-State-Machine-Editor#49] opened 2017-08-09 08:13 UTC
Pressing the "History Back" button directly after renaming a frame throws `Error 1 [..] at Property Node (arg 1) in CaseSelect__JKI_State_Machine_Helper.vi:3490001`.

<img width="336" alt="jkisme-error-rename" src="https://user-images.githubusercontent.com/7075830/29111574-1de2c8f4-7ceb-11e7-9f31-f9f197be985f.png">

**Comment by jimkring** [comment] 2018-03-29 21:57
hi @joerghampel. thanks for reporting this. I believe this has been fixed in recent releases. I just tested with the latest release and I could not reproduce it.  Please let us know if you still see this or any other issues. Thanks!

**Closed by jimkring** 2018-03-29 21:57 UTC
