### ISSUE TITLE
Labview 2017 support

### ISSUE THREAD

**Issue by moritzengineering** [JKISoftware/JKI-State-Machine-Editor#16] opened 2017-06-12 09:44 UTC
Is it correct that labview 2017 is not supported yet. cannot get it to work.
thanks.

**Comment by jimkring** [comment] 2017-06-16 19:11
The issue is actually that there's a package dependency that's missing. This will be resolved in the next release (shortly) or by installing the OpenG LabVIEW Data Tools package.

See Issue #19: OpenG LabVIEW Data dependency should be built in

**Closed by jimkring** 2017-06-16 19:11 UTC
